Updated bootstrap version to 0.18.13

diff --git a/fury b/fury
--- a/fury
+++ b/fury
@@ -6,12 +6,14 @@
 # Copyright 2018-20 Jon Pretty, Propensive OÜ.
 #
 
-version="0.18.0"
-ipfsHash="Qmc32p5q7MTsHQWnxoxBVPnX1xZQnfAfBkxKUbzvAjw3iV"
+version="0.18.13"
+ipfsHash="QmcjHx7JjuDWU6KhSS1m5L4ZLPHqFkSWKFKJemQ7YYdGAH"
+md5Hash="3e0e8d2c38f78679864aaf4e733d2771"
 xdgUsrHome="${XDG_DATA_HOME:-"$HOME/.local/share"}"
 xdgSysHome="${XDG_DATA_HOME:-/usr/share}"
 xdgHome="$([ "$EUID" = "0" ] && echo "${xdgSysHome}" || echo "${xdgUsrHome}")"
 furyDir="${xdgHome}/fury"
+jdkDir="${furyDir}/jdk"
 furyUsr="${furyDir}/usr"
 currentDir="${furyUsr}/current"
 currentVersion="$(head -n1 "${currentDir}/.version" 2> /dev/null || echo "")"
@@ -21,32 +23,88 @@ ipfsGateway="https://gateway.pinata.cloud/ipfs"
 downloadUrl="${ipfsGateway}/${ipfsHash}"
 installDir="${furyUsr}/$([ "${currentVersion}" = "${version}" ] && echo "current" || echo "${version}")"
 args="$@"
+info="\033[1m\033[42m INFO \033[0m "
+
 
 installFury() {
-  mkdir -p "${downloadDir}"
-  printf "Downloading Fury ${version}..."
+  checkJava && download && checkFile && extractTar
+}
+
+checkJava() {
+  (command -v java > /dev/null && command -v javac > /dev/null) || installJava
+}
+
+installJava() {
+  printf "${info}Installing a JDK..."
+  
+  case $(uname -s) in
+    Darwin*) os="mac" ;;
+    Linux*)  os="linux" ;;
+    CYGWIN*) os="windows" ;;
+    MINGW*)  os="windows" ;;
+    MSYS*)   os="windows" ;;
+    *)       fail os ;;
+  esac
+  
+  case $(uname -m) in
+    i386|i686|x86)                    arch="x32" ;;
+    x86_64|x64)                       arch="x64" ;;
+    aarch64_be|aarch64|armv8b|armv8l) arch="aarch64" ;;
+    arm)                              arch="arm" ;;
+    *)                                fail os ;;
+  esac
+  
   command -v curl > /dev/null || fail curl
+  mkdir -p "${jdkDir}"
+  curl -X GET -Ls "https://api.adoptopenjdk.net/v3/binary/latest/11/ga/${os}/${arch}/jdk/hotspot/normal/adoptopenjdk?project=jdk" -H "accept: */*" | tar xz -C "${jdkDir}"
+  mv "${jdkDir}"/*/* "${jdkDir}/"
+  printf "done\n"
+}
+
+runFury() {
+  printf "${info}Launching Fury ${version} in standalone mode...\n"
+  if [ -t 0 ]; then
+    FURY_HOME="${installDir}" "${installDir}/bin/fury" standalone ${args}
+  else
+    FURY_HOME="${installDir}" "${installDir}/bin/fury" standalone system install
+  fi
+}
+
+download() {
+  command -v curl > /dev/null || fail curl
+  mkdir -p "${downloadDir}"
+  printf "${info}Downloading Fury ${version}..."
   [ -f "${downloadFile}" ] || curl -Lso "${downloadFile}" "${downloadUrl}" || fail download
   printf "done\n"
-  printf "Extracting Fury ${version} into ${installDir}..."
+}
+
+checkFile() {
+  command -v md5sum > /dev/null || command -v md5 > /dev/null || fail md5sum
+  printf "${info}Checking MD5 checksum of ${downloadFile}..."
+  calcHash=$( (md5sum "${downloadFile}" 2> /dev/null || md5 -r "${downloadFile}" 2> /dev/null) | head -c 32)
+  [ "${md5Hash}" = "${calcHash}" ] || (rm -f "${downloadFile}" && fail checksum)
+  printf "done\n"
+}
+
+extractTar() {
+  printf "${info}Extracting Fury ${version} into ${installDir}..."
   command -v tar > /dev/null || fail tar
   mkdir -p "${installDir}" && tar xf "${downloadFile}" -C "${installDir}" || fail extract
   printf "done\n"
 }
 
-runFury() {
-  printf "Launching Fury ${version} in standalone mode...\n"
-  FURY_HOME="${installDir}" "${installDir}/bin/fury" standalone ${args}
-}
-
 fail() {
-  printf "fail\n"
+  printf "fail\n\033[1m\033[41m FAIL \033[0m \033[1m"
   case "$1" in
-    curl)     printf "Could not find `curl` to download Fury\n" ;;
-    download) printf "Could not download Fury version ${version}\n" ;;
-    tar)      printf "Could not find `tar` to extract Fury\n" ;;
-    extract)  printf "Could not extract Fury\n" ;;
+    curl)     printf "Could not find \033[0;36mcurl\033[0m, which is required to download Fury." ;;
+    download) printf "Could not download Fury version ${version}." ;;
+    tar)      printf "Could not find \033[0;36mtar\033[0m to extract Fury." ;;
+    extract)  printf "An unexpected error occurred while attempting to extract Fury." ;;
+    md5sum)   printf "Could not find \033[0;36mmd5sum\033[0m, which is necessary to check the integrity of the downloaded file." ;;
+    checksum) printf "The downloaded file fails the MD5 checksum test." ;;
+    os)       printf "A JDK could not be found, and the operating system type could not be identified to install one." ;;
   esac
+  printf "\033[0m\n"
   exit 1
 }
 
