fury restart functionality corrected

diff --git a/etc/fury b/etc/fury
--- a/etc/fury
+++ b/etc/fury
@@ -54,7 +54,7 @@ coursier() {
 stopFury() {
   nailgun "${FURY_MAIN}" "$$" "stop" 2> /dev/null
   case "$?" in
-    0)   nailgun ng-stop && exit 0 ;;
+    0)   nailgun ng-stop ;;
     230) echo "Fury is not running." && exit 1 ;;
     *)   exit 1 ;;
   esac
@@ -108,7 +108,15 @@ fury() {
 }
 
 restartFury() {
-  stopFury && ngServer
+  stopFury
+  if [ $? -eq 0 ]
+  then
+      echo "Restarting.."
+      ngServer && exit 0
+  else
+      echo "Failed to restart"
+      exit 1
+  fi
 }
 
 startFuryStandalone() {
