Don't run pending tests

diff --git a/etc/integration b/etc/integration
--- a/etc/integration
+++ b/etc/integration
@@ -58,10 +58,10 @@ if [ "$1" = "" ]; then
     runtest "$ROOT/test/passing" $ATEST && let APASSED="$APASSED+1" || { let AFAILED="$AFAILED+1"; AFAILURES+=($ATEST); }
   done
 
-  for BTEST in $(ls $ROOT/test/pending); do
-    let BCOUNT="$BCOUNT+1"
-    runtest "$ROOT/test/pending" $BTEST && let BPASSED="$BPASSED+1" || { let BFAILED="$BFAILED+1"; BFAILURES+=($BTEST); }
-  done
+  #for BTEST in $(ls $ROOT/test/pending); do
+  #  let BCOUNT="$BCOUNT+1"
+  #  runtest "$ROOT/test/pending" $BTEST && let BPASSED="$BPASSED+1" || { let BFAILED="$BFAILED+1"; BFAILURES+=($BTEST); }
+  #done
 
   echo ""
   echo "===================================================================================================="
@@ -69,9 +69,9 @@ if [ "$1" = "" ]; then
   echo "                   FAILED: $AFAILED    ${AFAILURES[@]}"
   echo "                    TOTAL: $ACOUNT"
 
-  echo " Pending tests     PASSED: $BPASSED"
-  echo "                   FAILED: $BFAILED    ${BFAILURES[@]}"
-  echo "                    TOTAL: $BCOUNT"
+  #echo " Pending tests     PASSED: $BPASSED"
+  #echo "                   FAILED: $BFAILED    ${BFAILURES[@]}"
+  #echo "                    TOTAL: $BCOUNT"
   echo "===================================================================================================="
   [ $ACOUNT = 0 ] && echo "No tests were run." && exit 1
   [ $ACOUNT = $APASSED ]
