Install Java if necessary

diff --git a/etc/launcher b/etc/launcher
--- a/etc/launcher
+++ b/etc/launcher
@@ -13,6 +13,7 @@ xdgUsrHome="${XDG_DATA_HOME:-"$HOME/.local/share"}"
 xdgSysHome="${XDG_DATA_HOME:-/usr/share}"
 xdgHome="$([ "$EUID" = "0" ] && echo "${xdgSysHome}" || echo "${xdgUsrHome}")"
 furyDir="${xdgHome}/fury"
+jdkDir="${furyDir}/jdk"
 furyUsr="${furyDir}/usr"
 currentDir="${furyUsr}/current"
 currentVersion="$(head -n1 "${currentDir}/.version" 2> /dev/null || echo "")"
@@ -24,6 +25,7 @@ installDir="${furyUsr}/$([ "${currentVersion}" = "${version}" ] && echo "current
 args="$@"
 info="\033[1m\033[42m INFO \033[0m "
 
+
 installFury() {
   checkJava && download && checkFile && extractTar
 }
@@ -32,6 +34,33 @@ checkJava() {
   printf "${info}Checking for \033[0;36mjava\033[0m on the path..."
   command -v java > /dev/null || fail java
   command -v javac > /dev/null || fail javac
+  printf "done\n"
+}
+
+installJava() {
+  printf "${info}Installing a JDK..."
+  
+  case $(uname -s) in
+    Darwin*) os="mac" ;;
+    Linux*)  os="linux" ;;
+    CYGWIN*) os="windows" ;;
+    MINGW*)  os="windows" ;;
+    MSYS*)   os="windows" ;;
+    *)       fail os ;;
+  esac
+  
+  case $(uname -m) in
+    i386|i686|x86)                    arch="x32" ;;
+    x86_64|x64)                       arch="x64" ;;
+    aarch64_be|aarch64|armv8b|armv8l) arch="aarch64" ;;
+    arm)                              arch="arm" ;;
+    *)                                fail os ;;
+  esac
+  
+  command -v curl > /dev/null || fail curl
+  mkdir -p "${jdkDir}"
+  curl -X GET -Ls "https://api.adoptopenjdk.net/v3/binary/latest/11/ga/${os}/${arch}/jdk/hotspot/normal/adoptopenjdk?project=jdk" -H "accept: */*" | tar xz -C "${jdkDir}"
+  mv "${jdkDir}/*/*" "${jdkDir}/"
   printf "done\n"
 }
 
@@ -78,6 +107,7 @@ fail() {
     extract)  printf "An unexpected error occurred while attempting to extract Fury." ;;
     md5sum)   printf "Could not find \033[0;36mmd5sum\033[0m, which is necessary to check the integrity of the downloaded file." ;;
     checksum) printf "The downloaded file fails the MD5 checksum test." ;;
+    os)       printf "A JDK could not be found, and the operating system type could not be identified to install one." ;;
   esac
   printf "\033[0m\n"
   exit 1
