Work in progress

diff --git a/etc/react b/etc/react
--- a/etc/react
+++ b/etc/react
@@ -14,6 +14,8 @@ else
   export FURY_HOME="$(cd "$(dirname "$0")"/.. && pwd -P)/.sandbox"
 fi
 
+echo "Running Fury in $FURY_HOME"
+
 export PATH="$FURY_HOME/bin:$PATH"
 TEST="$1"
 
@@ -23,7 +25,7 @@ init() {
 
 watchAndWait() {
   init
-  fury start
+  fury start || echo "Failed to start fury"
   echo "Running test $TEST..."
   source etc/integration "$TEST"
   fury kill
